### ISSUE TITLE
doesn't build 0.92 ghc7.8.4 nixpkgs

### ISSUE THREAD

**Issue by miguel-negrao** [kaoskorobase/hsc3-server#12]
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-haskell-hsc3-server-0.9.2.drv-0/Main.o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-build-haskell-hsc3-server-0.9.2.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2/lib/ghc-7.8.4/hsc3-server-0.9.2 --enable-split-objs --disable-library-profiling --enable-shared --enable-library-vanilla --enable-executable-dynamic --enable-tests
Configuring hsc3-server-0.9.2...
Flags chosen: build-examples=False
Dependency ListZipper -any: using ListZipper-1.2.0.2
Dependency QuickCheck >=2.4: using QuickCheck-2.7.6
Dependency base >=4.3 && <5: using base-4.7.0.2
Dependency bitset >=1.0: using bitset-1.4.8
Dependency bytestring -any: using bytestring-0.10.4.0
Dependency containers >=0.2: using containers-0.5.5.1
Dependency data-default >=0.5: using data-default-0.5.3
Dependency failure >=0.2: using failure-0.2.0.3
Dependency hashtables >=1.0: using hashtables-1.2.0.2
Dependency hosc >=0.14: using hosc-0.15
Dependency hsc3 >=0.15: using hsc3-0.15
Dependency hsc3-process ==0.10.*: using hsc3-process-0.10.0
Dependency hsc3-server >=0.8: using hsc3-server-0.9.2
Dependency lifted-base >=0.1: using lifted-base-0.2.3.6
Dependency monad-control >=0.3: using monad-control-1.0.0.4
Dependency random >=1.0: using random-1.1
Dependency resourcet >=0.3: using resourcet-1.1.4.1
Dependency test-framework -any: using test-framework-0.8.1.1
Dependency test-framework-quickcheck2 -any: using
test-framework-quickcheck2-0.3.0.3
Dependency transformers >=0.2: using transformers-0.3.0.0
Dependency transformers-base >=0.4: using transformers-base-0.4.4
Dependency unix >=2.5: using unix-2.7.0.1
/nix/store/rnxk1a1bz4rgy1rw4973blbfp9f0ic89-ghc-7.8.4/bin/ghc --info
Using Cabal-1.18.1.5 compiled by ghc-7.8
Using compiler: ghc-7.8.4
Using install prefix:
/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2
Binaries installed in:
/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2/bin
Libraries installed in:
/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2/lib/ghc-7.8.4/hsc3-server-0.9.2
Private binaries installed in:
/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2/libexec
Data files installed in:
/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2/share/x86_64-linux-ghc-7.8.4/hsc3-server-0.9.2
Documentation installed in:
/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2/share/doc/x86_64-linux-ghc-7.8.4/hsc3-server-0.9.2
Configuration files installed in:
/nix/store/iwrd3n08w1bsal3n5phm7v4xb7d0n9c2-haskell-hsc3-server-0.9.2/etc
No alex found
Using ar found on system at:
/nix/store/1j0vizfh6kalnkxjbchladh2f2q3wrgf-binutils-2.23.1/bin/ar
No c2hs found
No cpphs found
No ffihugs found
Using gcc version 4.8.4 given by user at:
/nix/store/qq15h6yahg9xjgnm55l66rsyp0bw2hix-gcc-wrapper-4.8.4/bin/gcc
Using ghc version 7.8.4 found on system at:
/nix/store/rnxk1a1bz4rgy1rw4973blbfp9f0ic89-ghc-7.8.4/bin/ghc
Using ghc-pkg version 7.8.4 found on system at:
/nix/store/rnxk1a1bz4rgy1rw4973blbfp9f0ic89-ghc-7.8.4/bin/ghc-pkg
No greencard found
Using haddock version 2.14.3 found on system at:
/nix/store/rnxk1a1bz4rgy1rw4973blbfp9f0ic89-ghc-7.8.4/bin/haddock
No happy found
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/rnxk1a1bz4rgy1rw4973blbfp9f0ic89-ghc-7.8.4/bin/hpc
Using hsc2hs version 0.67 found on system at:
/nix/store/rnxk1a1bz4rgy1rw4973blbfp9f0ic89-ghc-7.8.4/bin/hsc2hs
Using hscolour version 1.22 found on system at:
/nix/store/54gpgac4hayablp85w6hs7l8dk7gcz0y-hscolour-1.22/bin/HsColour
No hugs found
No jhc found
Using ld found on system at:
/nix/store/qq15h6yahg9xjgnm55l66rsyp0bw2hix-gcc-wrapper-4.8.4/bin/ld
No lhc found
No lhc-pkg found
No nhc98 found
No pkg-config found
Using ranlib found on system at:
/nix/store/1j0vizfh6kalnkxjbchladh2f2q3wrgf-binutils-2.23.1/bin/ranlib
Using strip found on system at:
/nix/store/1j0vizfh6kalnkxjbchladh2f2q3wrgf-binutils-2.23.1/bin/strip
Using tar found on system at:
/nix/store/s16y2pk8lljsm37b55h2dsl6gpbsb62g-gnutar-1.27.1/bin/tar
No uhc found
building
Building hsc3-server-0.9.2...
Preprocessing library hsc3-server-0.9.2...
[ 1 of 15] Compiling Sound.SC3.Server.Connection ( Sound/SC3/Server/Connection.hs, dist/build/Sound/SC3/Server/Connection.o )
[ 2 of 15] Compiling Sound.SC3.Server.Allocator.Range ( Sound/SC3/Server/Allocator/Range.hs, dist/build/Sound/SC3/Server/Allocator/Range.o )

Sound/SC3/Server/Allocator/Range.hs:22:1: Warning:
    Module ‘Prelude’ does not export ‘join’

Sound/SC3/Server/Allocator/Range.hs:157:1: Warning:
    Local definition of ‘join’ clashes with a future Prelude name - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
[ 3 of 15] Compiling Sound.SC3.Server.Allocator.BlockAllocator.FreeList ( Sound/SC3/Server/Allocator/BlockAllocator/FreeList.hs, dist/build/Sound/SC3/Server/Allocator/BlockAllocator/FreeList.o )
[ 4 of 15] Compiling Sound.SC3.Server.Allocator ( Sound/SC3/Server/Allocator.hs, dist/build/Sound/SC3/Server/Allocator.o )
[ 5 of 15] Compiling Sound.SC3.Server.Allocator.BlockAllocator.FirstFit ( Sound/SC3/Server/Allocator/BlockAllocator/FirstFit.hs, dist/build/Sound/SC3/Server/Allocator/BlockAllocator/FirstFit.o )
[ 6 of 15] Compiling Sound.SC3.Server.Allocator.SetAllocator ( Sound/SC3/Server/Allocator/SetAllocator.hs, dist/build/Sound/SC3/Server/Allocator/SetAllocator.o )
[ 7 of 15] Compiling Sound.SC3.Server.Allocator.SimpleAllocator ( Sound/SC3/Server/Allocator/SimpleAllocator.hs, dist/build/Sound/SC3/Server/Allocator/SimpleAllocator.o )
[ 8 of 15] Compiling Sound.SC3.Server.Allocator.Wrapped ( Sound/SC3/Server/Allocator/Wrapped.hs, dist/build/Sound/SC3/Server/Allocator/Wrapped.o )
[ 9 of 15] Compiling Sound.SC3.Server.State ( Sound/SC3/Server/State.hs, dist/build/Sound/SC3/Server/State.o )
[10 of 15] Compiling Sound.SC3.Server.Notification ( Sound/SC3/Server/Notification.hs, dist/build/Sound/SC3/Server/Notification.o )
[11 of 15] Compiling Sound.SC3.Server.State.Monad.Class ( Sound/SC3/Server/State/Monad/Class.hs, dist/build/Sound/SC3/Server/State/Monad/Class.o )
[12 of 15] Compiling Sound.SC3.Server.State.Monad ( Sound/SC3/Server/State/Monad.hs, dist/build/Sound/SC3/Server/State/Monad.o )

Sound/SC3/Server/State/Monad.hs:84:3:
    Wrong category of family instance; declaration was for a type synonym
    In the newtype instance declaration for ‘StM’
    In the instance declaration for ‘MonadBaseControl IO Server’
builder for ‘/nix/store/n5n4ccij0ipjw4v2k7dy5zmw9rc8kavi-haskell-hsc3-server-0.9.2.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/jvy5mrjnr42ggm8mdbsa9ia8j7157ncy-ghc-7.8.4.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/y7cd6inc4ilznr532fqn2n858a794lxh-ihaskell-with-packages.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/y7cd6inc4ilznr532fqn2n858a794lxh-ihaskell-with-packages.drv’ failed

**Comment by kaoskorobase** [comment]
hey miguel, fixed and released https://hackage.haskell.org/package/hsc3-server

**Comment by kaoskorobase** [comment]
and thanks for the report i forgot to say ;)

**Comment by miguel-negrao** [comment]
wow, that's what I call efficiency ! thanks !

Btw, why is the help not generated on hackage ? I see this sometimes happening on some versions of packages, but don't know what causes it...

**Comment by kaoskorobase** [comment]
i guess it just takes a while, afaik docs are processed asynchronously.

**Comment by miguel-negrao** [comment]
Very asynchronously, I would say ... :-) For instance hsc3 0.15.1 was uploaded on 21 April and still doesn't have documentation available.

**Comment by kaoskorobase** [comment]
just for the record, the documentation is online now: https://hackage.haskell.org/package/hsc3-server-0.10.0

**Comment by miguel-negrao** [comment]
Yes, I noticed too, and hsc3 also has documentation now (https://hackage.haskell.org/package/hsc3) so I imagine the documentation is generated maybe once per month on a specific day...
